package tk2_kelompok3;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP 14s Ryzen
 */
public class FrameKubusBetrin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameKubusBetrin.class.getName());

    /**
     * Creates new form FrameKubusBetrin
     */
    public FrameKubusBetrin() {
        initComponents();
        reset();
    }
    public void reset(){
        tSisi.setText(null);
        lLuasPermukaan.setText("0");
        lVolume.setText("0");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tSisi = new javax.swing.JTextField();
        lLuasPermukaan = new javax.swing.JLabel();
        lVolume = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(910, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tSisi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tSisi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tSisi.addActionListener(this::tSisiActionPerformed);
        tSisi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tSisiKeyReleased(evt);
            }
        });
        jPanel1.add(tSisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 290, 40));

        lLuasPermukaan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lLuasPermukaan.setForeground(new java.awt.Color(255, 255, 255));
        lLuasPermukaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLuasPermukaan.setText("0");
        jPanel1.add(lLuasPermukaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 140, 40));

        lVolume.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lVolume.setForeground(new java.awt.Color(255, 255, 255));
        lVolume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lVolume.setText("0");
        jPanel1.add(lVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 140, 40));

        btnKembali.setBackground(new java.awt.Color(36, 93, 196));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 360, 40));

        btnHitung.setBackground(new java.awt.Color(36, 93, 196));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 170, 40));

        btnReset.setBackground(new java.awt.Color(36, 93, 196));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok3/Icon/Background Kubus.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        KubusBetrin kubus = new KubusBetrin();
        kubus.setSisi(Double.parseDouble(tSisi.getText()));
        
        kubus.luasPermukaan();
        kubus.volume();
        
        lLuasPermukaan.setText(String.valueOf(kubus.luasPermukaan()));
        lVolume.setText(String.valueOf(kubus.volume()));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new DashboardFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
        tSisi.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tSisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSisiActionPerformed
        // TODO add your handling code here:
        btnHitung.doClick();
    }//GEN-LAST:event_tSisiActionPerformed

    private void tSisiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSisiKeyReleased
        // TODO add your handling code here:
        btnHitung.doClick();
    }//GEN-LAST:event_tSisiKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameKubusBetrin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lLuasPermukaan;
    private javax.swing.JLabel lVolume;
    private javax.swing.JTextField tSisi;
    // End of variables declaration//GEN-END:variables
}
