/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tk2_kelompok3;

/**
 *
 * @author user
 */
public class FrameBalok extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameBalok.class.getName());

    /**
     * Creates new form FrameBalok
     */
    public FrameBalok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tVolume = new javax.swing.JLabel();
        tLuasPermukaan = new javax.swing.JLabel();
        bHitung = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        tLebar = new javax.swing.JTextField();
        tPanjang = new javax.swing.JTextField();
        tTinggi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tVolume.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        tVolume.setForeground(new java.awt.Color(255, 255, 255));
        tVolume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tVolume.setText("0");
        jPanel1.add(tVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 200, -1));

        tLuasPermukaan.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        tLuasPermukaan.setForeground(new java.awt.Color(255, 255, 255));
        tLuasPermukaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLuasPermukaan.setText("0");
        jPanel1.add(tLuasPermukaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 200, -1));

        bHitung.setBackground(new java.awt.Color(36, 93, 196));
        bHitung.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bHitung.setForeground(new java.awt.Color(255, 255, 255));
        bHitung.setText("HITUNG");
        bHitung.addActionListener(this::bHitungActionPerformed);
        jPanel1.add(bHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 170, 50));

        jButton1.setBackground(new java.awt.Color(36, 93, 196));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KEMBALI");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 360, 60));

        bReset.setBackground(new java.awt.Color(36, 93, 196));
        bReset.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("RESET");
        bReset.addActionListener(this::bResetActionPerformed);
        jPanel1.add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 180, 50));

        tLebar.setBackground(new java.awt.Color(255, 255, 255));
        tLebar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tLebar.setForeground(new java.awt.Color(10, 37, 86));
        tLebar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tLebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        tLebar.addActionListener(this::tLebarActionPerformed);
        jPanel1.add(tLebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 300, 60));

        tPanjang.setBackground(new java.awt.Color(255, 255, 255));
        tPanjang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tPanjang.setForeground(new java.awt.Color(10, 37, 86));
        tPanjang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tPanjang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        tPanjang.addActionListener(this::tPanjangActionPerformed);
        jPanel1.add(tPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 300, 60));

        tTinggi.setBackground(new java.awt.Color(255, 255, 255));
        tTinggi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tTinggi.setForeground(new java.awt.Color(10, 37, 86));
        tTinggi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tTinggi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        tTinggi.addActionListener(this::tTinggiActionPerformed);
        jPanel1.add(tTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 300, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok3/Icon/Background Balok.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPanjangActionPerformed
        // TODO add your handling code here:
         tLebar.requestFocus();
        
    }//GEN-LAST:event_tPanjangActionPerformed

    private void tTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTinggiActionPerformed
        // TODO add your handling code here:
         bHitung.doClick();
    }//GEN-LAST:event_tTinggiActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        BalokBagas balok = new BalokBagas();

        balok.setPanjang(Double.parseDouble(tPanjang.getText()));
        balok.setLebar(Double.parseDouble(tLebar.getText()));
        balok.setTinggi(Double.parseDouble(tTinggi.getText()));

        balok.volume();
        balok.LuasPermukaaan();

        tVolume.setText(String.valueOf(balok.getVolume()));
        tLuasPermukaan.setText(String.valueOf(balok.getLuasPermukaan()));
    }//GEN-LAST:event_bHitungActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        tPanjang.setText(null);
        tLebar.setText(null);
        tTinggi.setText(null);
        tVolume.setText("0");
        tLuasPermukaan.setText("0");
        tPanjang.requestFocus();
    }//GEN-LAST:event_bResetActionPerformed

    private void tLebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLebarActionPerformed
        // TODO add your handling code here:
         tTinggi.requestFocus();
    }//GEN-LAST:event_tLebarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameBalok().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tLebar;
    private javax.swing.JLabel tLuasPermukaan;
    private javax.swing.JTextField tPanjang;
    private javax.swing.JTextField tTinggi;
    private javax.swing.JLabel tVolume;
    // End of variables declaration//GEN-END:variables
}
