/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tk2_kelompok3;

/**
 *
 * @author ACER
 */
public class FrameKerucut extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameKerucut.class.getName());

    /**
     * Creates new form FrameKerucut
     */
    public FrameKerucut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tLuaspermukaan = new javax.swing.JLabel();
        tVolume = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        tJarijari = new javax.swing.JTextField();
        tTinggi = new javax.swing.JTextField();
        tGaris = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tLuaspermukaan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tLuaspermukaan.setForeground(new java.awt.Color(255, 255, 255));
        tLuaspermukaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLuaspermukaan.setText("0");
        jPanel1.add(tLuaspermukaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 290, 40));

        tVolume.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tVolume.setForeground(new java.awt.Color(255, 255, 255));
        tVolume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tVolume.setText("0");
        jPanel1.add(tVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 290, 40));

        jButton1.setBackground(new java.awt.Color(36, 93, 196));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KEMBALI");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 360, 60));

        btnHitung.setBackground(new java.awt.Color(36, 93, 196));
        btnHitung.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(this::btnHitungActionPerformed);
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 150, 40));

        btnReset.setBackground(new java.awt.Color(36, 93, 196));
        btnReset.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(this::btnResetActionPerformed);
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 423, 160, 40));

        tJarijari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tJarijari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tJarijari.addActionListener(this::tJarijariActionPerformed);
        jPanel1.add(tJarijari, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 290, 40));

        tTinggi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tTinggi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tTinggi.addActionListener(this::tTinggiActionPerformed);
        jPanel1.add(tTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 290, 40));

        tGaris.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tGaris.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tGaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 290, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok3/Icon/Background Kerucut.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        KerucutFarid kerucut = new KerucutFarid();

        kerucut.setJariJari(Double.parseDouble(tJarijari.getText()));
        kerucut.setTinggi(Double.parseDouble(tTinggi.getText()));
        kerucut.setGarisPelukis(Double.parseDouble(tGaris.getText()));

        kerucut.volume();
        kerucut.luasPermukaan();

        tVolume.setText(String.valueOf(kerucut.getVolume()));
        tLuaspermukaan.setText(String.valueOf(kerucut.getLuasPermukaan()));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tJarijari.setText("");
        tTinggi.setText("");
        tGaris.setText("");
        tVolume.setText("0");
        tLuaspermukaan.setText("0");
       
    }//GEN-LAST:event_btnResetActionPerformed

    private void tTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTinggiActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new DashboardFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tJarijariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJarijariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJarijariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameKerucut().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tGaris;
    private javax.swing.JTextField tJarijari;
    private javax.swing.JLabel tLuaspermukaan;
    private javax.swing.JTextField tTinggi;
    private javax.swing.JLabel tVolume;
    // End of variables declaration//GEN-END:variables
}
