/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.*;

/**
 *
 * @author Lenovo
 */
public class FrameBola extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameBola.class.getName());

    /**
     * Creates new form FrameBola
     */
    public FrameBola() {
        initComponents();
        tNama.setText("Selamat Datang, " + user.namaUser + " Di Frame Bola");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tNama = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        tVolume = new javax.swing.JLabel();
        tLuasPermukaan = new javax.swing.JLabel();
        tJariJari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNama.setForeground(new java.awt.Color(255, 255, 255));
        tNama.setText("jLabel");
        tNama.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tNamaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 410, 40));

        jButton1.setBackground(new java.awt.Color(36, 93, 196));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KEMBALI");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 360, 60));

        btnHitung.setBackground(new java.awt.Color(36, 93, 196));
        btnHitung.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(this::btnHitungActionPerformed);
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 170, 50));

        btnReset.setBackground(new java.awt.Color(36, 93, 196));
        btnReset.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(this::btnResetActionPerformed);
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 420, 170, 50));

        tVolume.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tVolume.setForeground(new java.awt.Color(255, 255, 255));
        tVolume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tVolume.setText("0");
        jPanel1.add(tVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 210, 60));

        tLuasPermukaan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tLuasPermukaan.setForeground(new java.awt.Color(255, 255, 255));
        tLuasPermukaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLuasPermukaan.setText("0");
        jPanel1.add(tLuasPermukaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 210, 60));

        tJariJari.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tJariJari.setForeground(new java.awt.Color(10, 37, 86));
        tJariJari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tJariJari, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 300, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok3/Icon/Background Bola.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try {
            // Nama: Mohamad Syifa'ul Amal - 202557201025
            BolaFaul bola = new BolaFaul();

            double r = Double.parseDouble(tJariJari.getText());
            bola.setJariJari(r);

            bola.volume();
            bola.luasPermukaan();

            tVolume.setText(String.format("%.2f", bola.getVolume()));
            tLuasPermukaan.setText(String.format("%.2f", bola.getLuasPermukaan()));

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Input jari-jari harus angka!");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    tJariJari.setText("");
    tVolume.setText("0");
    tLuasPermukaan.setText("0");
    tJariJari.requestFocus();

    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new DashboardFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new DashboardFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tNamaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tNamaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameBola().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tJariJari;
    private javax.swing.JLabel tLuasPermukaan;
    private javax.swing.JLabel tNama;
    private javax.swing.JLabel tVolume;
    // End of variables declaration//GEN-END:variables
}
