/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.*;

/**
 *
 * @author User
 */
public class FrameTabungNatasza extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameTabungNatasza.class.getName());

    /**
     * Creates new form FrameTabungNatasza
     */
    public FrameTabungNatasza() {
        initComponents();
        tNama.setText("Selamat Datang, " + user.namaUser + " Di Frame Tabung");
        reset();
    }
    public void reset(){
       tJariJari.setText(null);
       tTinggi.setText(null);
       tLuasPermukaan.setText("0");
       tVolume.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tNama = new javax.swing.JLabel();
        tTinggi = new javax.swing.JTextField();
        tJariJari = new javax.swing.JTextField();
        tVolume = new javax.swing.JLabel();
        tLuasPermukaan = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(910, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(910, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tNama.setForeground(new java.awt.Color(255, 255, 255));
        tNama.setText("jLabel2");
        jPanel1.add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 400, 40));

        tTinggi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tTinggi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tTinggi.addActionListener(this::tTinggiActionPerformed);
        jPanel1.add(tTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 300, 50));

        tJariJari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tJariJari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tJariJari.addActionListener(this::tJariJariActionPerformed);
        jPanel1.add(tJariJari, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 300, 50));

        tVolume.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tVolume.setForeground(new java.awt.Color(255, 255, 255));
        tVolume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tVolume.setText("0");
        jPanel1.add(tVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 240, 40));

        tLuasPermukaan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tLuasPermukaan.setForeground(new java.awt.Color(255, 255, 255));
        tLuasPermukaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLuasPermukaan.setText("0");
        jPanel1.add(tLuasPermukaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 240, 40));

        btnReset.setBackground(new java.awt.Color(36, 93, 196));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 170, 40));

        btnHitung.setBackground(new java.awt.Color(36, 93, 196));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 170, 40));

        btnKembali.setBackground(new java.awt.Color(36, 93, 196));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 350, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok3/Icon/Background Tabung (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
        tJariJari.requestFocus();
        tTinggi.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tJariJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJariJariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJariJariActionPerformed

    private void tTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTinggiActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        TabungNatasza tabung = new TabungNatasza();
        tabung.setJariJari(Double.parseDouble(tJariJari.getText()));
        tabung.setTinggi(Double.parseDouble(tTinggi.getText()));
        
        tabung.luasPermukaan();
        tabung.volume();
        
        tLuasPermukaan.setText(String.valueOf(tabung.luasPermukaan()));
        tVolume.setText(String.valueOf(tabung.volume()));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new DashboardFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameTabungNatasza().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tJariJari;
    private javax.swing.JLabel tLuasPermukaan;
    private javax.swing.JLabel tNama;
    private javax.swing.JTextField tTinggi;
    private javax.swing.JLabel tVolume;
    // End of variables declaration//GEN-END:variables
}
