/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template.
 */
package view;

import model.*;

/**
 *
 * @author macbookairm12020
 */
public class FrameLimassegiempat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameLimassegiempat.class.getName());

    /**
     * Creates new form FrameLimassegiempat
     */
    //dwi
    public FrameLimassegiempat() {
        initComponents();
        
        reset ();
    }
    void reset(){
           tSisialas.setText(null);
        tTinggilimas.setText(null);
        tTinggisisi.setText(null);
        tVolume.setText("0");
        tLuasPermukaan.setText("0");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tLuasPermukaan = new javax.swing.JLabel();
        tVolume = new javax.swing.JLabel();
        bHitung = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tSisialas = new javax.swing.JTextField();
        tTinggilimas = new javax.swing.JTextField();
        tTinggisisi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tLuasPermukaan.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        tLuasPermukaan.setForeground(new java.awt.Color(255, 255, 255));
        tLuasPermukaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLuasPermukaan.setText("0");
        jPanel1.add(tLuasPermukaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 200, -1));

        tVolume.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        tVolume.setForeground(new java.awt.Color(255, 255, 255));
        tVolume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tVolume.setText("0");
        jPanel1.add(tVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 200, -1));

        bHitung.setBackground(new java.awt.Color(36, 93, 196));
        bHitung.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bHitung.setForeground(new java.awt.Color(255, 255, 255));
        bHitung.setText("HITUNG");
        bHitung.addActionListener(this::bHitungActionPerformed);
        jPanel1.add(bHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 170, 50));

        bReset.setBackground(new java.awt.Color(36, 93, 196));
        bReset.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("RESET");
        bReset.addActionListener(this::bResetActionPerformed);
        jPanel1.add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 180, 50));

        jButton1.setBackground(new java.awt.Color(36, 93, 196));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KEMBALI");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 360, 60));

        tSisialas.addActionListener(this::tSisialasActionPerformed);
        jPanel1.add(tSisialas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 290, 40));

        tTinggilimas.addActionListener(this::tTinggilimasActionPerformed);
        jPanel1.add(tTinggilimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 290, 40));
        jPanel1.add(tTinggisisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 290, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok3/Icon/Background Limas.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 910, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tSisialasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSisialasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSisialasActionPerformed

    private void tTinggilimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTinggilimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTinggilimasActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        DwiLimassegiempat limas = new DwiLimassegiempat();

        limas.setSisiAlas(Double.parseDouble(tSisialas.getText()));
        limas.setTinggiLimas(Double.parseDouble(tTinggilimas.getText()));
        limas.setTinggiSisi(Double.parseDouble(tTinggisisi.getText()));

        limas.volume();
        limas.luasPermukaan();

        tVolume.setText(String.valueOf(limas.getVolume()));
        tLuasPermukaan.setText(String.valueOf(limas.getLuasPermukaan()));
    }//GEN-LAST:event_bHitungActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
       reset();
    }//GEN-LAST:event_bResetActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new DashboardFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameLimassegiempat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tLuasPermukaan;
    private javax.swing.JTextField tSisialas;
    private javax.swing.JTextField tTinggilimas;
    private javax.swing.JTextField tTinggisisi;
    private javax.swing.JLabel tVolume;
    // End of variables declaration//GEN-END:variables
}
